### ISSUE TITLE
Error: Text data outside root node

### ISSUE THREAD

**Issue by t3rminus** [edwellbrook/node-tvdb#80]
Not sure why I'm getting this error. Could be a data issue with TVDB?
```Error: Text data outside of root node.
Line: 1
Column: 1
Char: C
    at error (/node_modules/sax/lib/sax.js:667:10)
    at strictFail (/node_modules/sax/lib/sax.js:693:7)
    at Object.write (/node_modules/sax/lib/sax.js:1051:15)
    at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/xml2js.js:508:31)
    at Parser.bind [as parseString] (/node_modules/xml2js/lib/xml2js.js:7:59)
    at exports.parseString (/node_modules/xml2js/lib/xml2js.js:540:19)
    at parseXML (/node_modules/node-tvdb/index.js:415:5)
    at Request._callback (/node_modules/node-tvdb/index.js:399:17)
    at Request.init.self.callback (/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)```

**Comment by edwellbrook** [comment]
Looks like it was an issue with the response TVDB gave and there's not too much I can do about that. Also, unfortunately you're using an older version of the API (XML based) and client. I'd recommend you use the latest version of `node-tvdb` which uses their JSON API and is actively worked on.

Please let me know if you need any help migrating versions.

**Comment by t3rminus** [comment]
I should be fine migrating-- I'm kind-of curious why I got the XML-based API client to begin with, though. My project isn't that old. When was the switch made?

**Comment by edwellbrook** [comment]
Switch was made late December last year with the release of `v3.0.0` so fairly recently.

Closing this issue for now, but please feel free to open another with any issues/questions you come across :)
